//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyImage
    {
        public int imageId { get; set; }
        public int propertyId { get; set; }
        public string imagePath { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
