//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int rentalId { get; set; }
        public int userId { get; set; }
        public string clientName { get; set; }
        public string clientEmail { get; set; }
        public string clientContact { get; set; }
        public string clientLocation { get; set; }
        public decimal rent { get; set; }
        public string billingPeriod { get; set; }
        public string due { get; set; }
    
        public virtual User User { get; set; }
    }
}
